# Generated by Django 4.2.7 on 2026-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_receipt_alter_sale_id_alter_sale_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=200),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
