# Generated by Django 6.0.3 on 2026-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_receipt_customer_name_receipt_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
